name: Build & Deploy .NET + Terraform

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "9.0"

    - name: Publish .NET API
      run: |
        PROJECT=$(find ./netapiapp -name "*.csproj")
        dotnet publish $PROJECT -c Release -o ./netapiapp/published
        cd ./netapiapp/published
        zip -r ../published.zip .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Terraform Azure Credentials
      run: |
        echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: ./terraform/env/dev
      run: terraform init -upgrade

    - name: Terraform Plan
      working-directory: ./terraform/env/dev
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./terraform/env/dev
      run: terraform apply -auto-approve

    - name: Get Terraform Output (WebApp Name)
      id: tf-output
      working-directory: ./terraform/env/dev
      run: |
        APP_URL=$(terraform output -raw app_url)
        {
          echo "app_url<<EOF"
          echo "$APP_URL"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"


    - name: Deploy WebApp ZIP
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.tf-output.outputs.webapp }}
        package: "./netapiapp/published.zip"
