name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to confirm destroy"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    if: ${{ github.event.inputs.confirm == 'YES' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve tfplan
